/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.polycafe.ui;

import com.poly.polycafe.entity.User;
import com.poly.polycafe.ui.manager.BillManagerJDialog;
import com.poly.polycafe.ui.manager.CardManagerJDialog;
import com.poly.polycafe.ui.manager.CategoryManagerJDialog;
import com.poly.polycafe.ui.manager.DrinkManagerJDialog;
import com.poly.polycafe.ui.manager.RevenueManagerJDialog;
import com.poly.polycafe.ui.manager.UserManagerJDialog;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import lombok.*;
/**
 *
 * @author Gaudomun
 */
@Getter @Setter
public class ManagerJFrame extends javax.swing.JFrame {
    private JDialog historyDialog;
    private User user;
    
    /**
     * Creates new form MainUi
     */
    public ManagerJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlButtons = new javax.swing.JPanel();
        btnSales = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlProfile = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlControl = new javax.swing.JPanel();
        pnlControlButtons = new javax.swing.JPanel();
        btnDrinkMgr = new javax.swing.JButton();
        btnCategoriesMgr = new javax.swing.JButton();
        btnCardMgr = new javax.swing.JButton();
        btnBillMgr = new javax.swing.JButton();
        btnUserMgr = new javax.swing.JButton();
        btnRevenueMgr = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pnlBackground = new javax.swing.JPanel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POLYCAFE");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.BorderLayout(5, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        pnlButtons.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        btnSales.setText("BÁN HÀNG");
        btnSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSales);

        btnHistory.setText("LỊCH SỬ");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        pnlButtons.add(btnHistory);

        btnChangePassword.setText("ĐỔI MẬT KHẨU");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        pnlButtons.add(btnChangePassword);

        btnExit.setText("KẾT THÚC");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlButtons.add(btnExit);

        jPanel1.add(pnlButtons, java.awt.BorderLayout.PAGE_END);

        lblProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(0, 51, 255));
        lblUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        javax.swing.GroupLayout pnlProfileLayout = new javax.swing.GroupLayout(pnlProfile);
        pnlProfile.setLayout(pnlProfileLayout);
        pnlProfileLayout.setHorizontalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        pnlProfileLayout.setVerticalGroup(
            pnlProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel1.add(pnlProfile, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        pnlControl.setOpaque(false);
        pnlControl.setLayout(new java.awt.BorderLayout());

        pnlControlButtons.setOpaque(false);
        pnlControlButtons.setLayout(new java.awt.GridLayout(2, 3, 5, 5));

        btnDrinkMgr.setText("ĐỒ UỐNG");
        btnDrinkMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrinkMgrActionPerformed(evt);
            }
        });
        pnlControlButtons.add(btnDrinkMgr);

        btnCategoriesMgr.setText("LOẠI ĐỒ UỐNG");
        btnCategoriesMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriesMgrActionPerformed(evt);
            }
        });
        pnlControlButtons.add(btnCategoriesMgr);

        btnCardMgr.setText("THẺ ĐỊNH DANH");
        btnCardMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCardMgrActionPerformed(evt);
            }
        });
        pnlControlButtons.add(btnCardMgr);

        btnBillMgr.setText("PHIẾU BÁN HÀNG");
        btnBillMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillMgrActionPerformed(evt);
            }
        });
        pnlControlButtons.add(btnBillMgr);

        btnUserMgr.setText("NGƯỜI DÙNG");
        btnUserMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserMgrActionPerformed(evt);
            }
        });
        pnlControlButtons.add(btnUserMgr);

        btnRevenueMgr.setText("DOANH THU");
        btnRevenueMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueMgrActionPerformed(evt);
            }
        });
        pnlControlButtons.add(btnRevenueMgr);

        pnlControl.add(pnlControlButtons, java.awt.BorderLayout.PAGE_END);

        jPanel4.setOpaque(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        pnlControl.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnlControl);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coffee-shop_resize.jpg"))); // NOI18N
        lblBackground.setOpaque(true);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        jPanel2.add(pnlBackground);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
        LoginJDialog login = new LoginJDialog(new javax.swing.JFrame(), true);
        login.setVisible(true);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCardMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCardMgrActionPerformed
        CardManagerJDialog card = new CardManagerJDialog(new javax.swing.JFrame(), true);
        card.setVisible(true);
    }//GEN-LAST:event_btnCardMgrActionPerformed

    private void btnUserMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserMgrActionPerformed
        UserManagerJDialog user = new UserManagerJDialog(new javax.swing.JFrame(), true);
        user.setVisible(true);
    }//GEN-LAST:event_btnUserMgrActionPerformed

    private void btnCategoriesMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriesMgrActionPerformed
        CategoryManagerJDialog category = new CategoryManagerJDialog(new javax.swing.JFrame(), true);
        category.setVisible(true);
    }//GEN-LAST:event_btnCategoriesMgrActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        ChangePasswordJDialog changePass = new ChangePasswordJDialog(new javax.swing.JFrame(), true);
        changePass.setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnDrinkMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrinkMgrActionPerformed
        DrinkManagerJDialog drinkMgr = new DrinkManagerJDialog(new javax.swing.JFrame(), true);
        drinkMgr.setVisible(true);
    }//GEN-LAST:event_btnDrinkMgrActionPerformed

    private void btnBillMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillMgrActionPerformed
        BillManagerJDialog billMgr = new BillManagerJDialog(new javax.swing.JFrame(), true);
        billMgr.setVisible(true);
    }//GEN-LAST:event_btnBillMgrActionPerformed

    private void btnRevenueMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueMgrActionPerformed
        RevenueManagerJDialog revenueDialog = new RevenueManagerJDialog(new javax.swing.JFrame(), true);
        revenueDialog.setVisible(true);
    }//GEN-LAST:event_btnRevenueMgrActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        historyDialog.setVisible(true);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesActionPerformed
        SalesJDialog sales = new SalesJDialog(this, true);
        sales.setUser(user);
        sales.setVisible(true);
 
    }//GEN-LAST:event_btnSalesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.showUserInfo();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillMgr;
    private javax.swing.JButton btnCardMgr;
    private javax.swing.JButton btnCategoriesMgr;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnDrinkMgr;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnRevenueMgr;
    private javax.swing.JButton btnSales;
    private javax.swing.JButton btnUserMgr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlControlButtons;
    private javax.swing.JPanel pnlProfile;
    // End of variables declaration//GEN-END:variables
    
    public void showUserInfo() {
        lblUserName.setText(user.getUsername());
        lblProfile.setIcon(new ImageIcon(getClass().getResource("/images/" + user.getPhoto())));
    }
}
