/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.poly.polycafe.ui;

import com.poly.polycafe.controller.SalesController;
import com.poly.polycafe.dao.BillDAO;
import com.poly.polycafe.dao.CardDAO;
import com.poly.polycafe.daoimpl.BillDAOImpl;
import com.poly.polycafe.daoimpl.CardDAOImpl;
import com.poly.polycafe.entity.Bill;
import com.poly.polycafe.entity.Card;
import com.poly.polycafe.entity.User;
import com.poly.polycafe.ui.manager.BillManagerJDialog;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JButton;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Gaudomun
 */
@Getter @Setter
public class SalesJDialog extends javax.swing.JDialog implements SalesController {
    private User user;
    /**
     * Creates new form SalesJDialog
     */
    public SalesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCards = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thẻ định danh");
        setPreferredSize(new java.awt.Dimension(600, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlCards.setLayout(new java.awt.GridLayout(0, 6, 5, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCards, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCards, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.open();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SalesJDialog dialog = new SalesJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlCards;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        this.setLocationRelativeTo(null);
        this.loadCards();
    }

    @Override
    public void showBill(int cardId) {
        BillDAO dao = new BillDAOImpl();
        Bill bill = dao.findServicingByCardId(cardId);
        BillManagerJDialog dialog = new BillManagerJDialog((Frame)this.getOwner(), true);
        dialog.setBilll(bill);
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(null);
    }
    
    public void showOrder(int cardId) {
        BillJDialog dialog = new BillJDialog((Frame)this.getOwner(), true);
        dialog.setCardId(cardId);
        dialog.setUser(user);
        dialog.setVisible(true);
        dialog.setLocationRelativeTo(null);
    }
    
    private void loadCards() {
        CardDAO cardDao = new CardDAOImpl();
        List<Card> cards = cardDao.findAll();
        pnlCards.removeAll();
        cards.forEach(card -> pnlCards.add(createButton(card)));
    }

    private JButton createButton(Card card) {
        JButton btnCard = new JButton();
        btnCard.setText(String.format("Card #%d", card.getId()));
        btnCard.setPreferredSize(new Dimension(50, 80));
        btnCard.setEnabled(card.getStatus() == 1);
        btnCard.setBackground(btnCard.isEnabled()? Color.GREEN : Color.GRAY);
        btnCard.setActionCommand(String.valueOf(card.getId()));
        btnCard.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                int cardId = Integer.parseInt(e.getActionCommand());
                System.out.println(cardId);
                SalesJDialog.this.showOrder(cardId);
            }
        });
        return btnCard;
    }
    
}
